# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michelangelo Riccobene 
title: Computer Engineer (MSc), Ethereum Core dev, Blockchain/trustless application architect
email: 
website: www.github.com/mriccobene

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: rimichelangelo
github_username:  mriccobene
# stackoverflow_username: "00000001"
# dribbble_username: mike
# facebook_username: mike
# flickr_username: mike
#instagram_username: mike
linkedin_username: michelangeloriccobene
# xing_username: mike
# pinterest_username: mike
#youtube_username: mike
# googleplus_username: +mike
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: about.me
  icon: fas fa-globe
  url: http://about.me/rimic
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.gif
about_content: | # this will include new lines to allow paragraphs
  I design and build software systems taking into account <mark>architectural issues</mark> and human factors.

  My professional interests concern <mark>trustiness</mark> <mark>security</mark> and <mark>reliability</mark> of systems, 
  software architecture and the qualities it determines, as well as human-machine interaction. 
  
  I am an Ethereum core dev and I also design trustless applications using <mark>blockchain</mark>, <mark>cryptography</mark> and <mark>software engineering</mark>.
  Additionally, I am exploring how <mark>generative AI</mark> can endow applications with conversational intelligence and gradually make obsolete parts of conventional software.
  
  I have written software using <mark>programming languages</mark> like C++, Java, Python, JavaScript/TypeScript, Solidity.

  I live and swim in Genoa.

  Ah, I think code is mostly for <mark>humans</mark> rather than for machines ;-)
  

content:
     
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Erigon (Ethereum EL/CL client)
        link: github.com/erigontech/erigon
        quote: >
          An open-source Ethereum client written in Go, designed for high performance and modularity.
        description: |
          As part of the Erigon core team, I work on the design and development of the QA system that assesses the <mark>stability</mark> and <mark>performance</mark> of the client.

          The main pillars of our QA system are:

          • Writing and running <mark>end-to-end tests</mark> to continuously assess the stability of Erigon across multiple chains (Ethereum, Gnosis, etc.).
          • Collecting detailed <mark>performance measurements</mark> during test execution to identify regressions through a Change Point Detection system.
          • Gathering and analyzing <mark>profiling data</mark> to provide developers with actionable insights for optimizing Erigon’s performance.
          
          The QA infrastructure we developed includes self-hosted test runners, automated workflows integrated with <mark>GitHub Actions</mark>, test scripts, and dashboards (Grafana + MongoDB) for visualizing test metrics and trends.
          Each test runner is configured using <mark>Ansible</mark> and is fully observable and controllable through a management application, which can be accessed via a web UI or automation scripts.
          There is also a dedicated system for building preconfigured Erigon databases and distributing them to the machines that require them for testing.

      - layout: top-middle
        title: Silkworm (Ethereum EL client)
        link: github.com/erigontech/silkworm
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Open source C++ implementation of the Ethereum Execution Layer (EL) protocol.
        description: | # this will include new lines to allow paragraphs
          Silkworm is a greenfield <mark>C++</mark> implementation of the <mark>Ethereum</mark> Execution Layer (EL) protocol based on the [Erigon Thorax architecture](https://github.com/ledgerwatch/erigon#key-features). 
          It aims to be the fastest Ethereum EL client while maintaining the high quality and readability of its source code. 
          
          I contributed to the project by developing the C++ version of the header and body downloader for Proof of Work (PoW), adapting the innovative approach originally devised in Erigon. 
          
          Furthermore, I played a supportive role in the integration of Proof of Stake (PoS), specifically by implementing an inversion of control strategy as envisioned by our lead developer. 
          This pivotal modification transformed the operational dynamic, enabling the Consensus Layer (CL) to direct the EL. This shift away from an EL-centric loop involving the CL to a more 
          flexible architecture made it possible to plug different CL algorithms into the system, significantly enhancing its adaptability and performance.
          
      - layout: top-middle
        title: Folks Finance
        link: folks.finance
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A capital markets protocol for borrowing and lending built on the top of the Algorand blockchain.
        description: | # this will include new lines to allow paragraphs
          [Folks Finance](https://folks.finance/) is a DeFi (<mark>Decentralized Finance</mark>) project developed by Blockchain Italia. 
          I was instrumental in laying the foundation for this project and have been part of the team since its inception. 
          
          My role involved drafting the initial design of the protocol on the Algorand blockchain, at a time when there were no DeFi projects on Algorand 
          and skepticism existed regarding the feasibility of such implementations. 
          
          My contributions also included the development of the core mathematical models and their practical implementation, 
          thereby establishing the groundwork for what would become a pioneering DeFi service on the Algorand platform.
          
      - layout: top-middle
        title: Ethereum Gateway
        # link: github.com/ethereum-gw
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A serverless application that uses AWS Step Functions workflow to model an Ethereum transaction life cycle. 
          It signs & submits a tx, tracks its outcome, speeds up or recovers it if lost.
        description: | # this will include new lines to allow paragraphs
          The application enables an enterprise component to interact with an Ethereum-like blockchain 
          using an HTTP REST interface hiding the underlying details.

          The project uses the <mark>serverless framework</mark> [(see here)](https://www.serverless.com/) so that the owner only pays when he/she uses it; 
          it generates an [AWS Api Gateway](https://aws.amazon.com/it/api-gateway/) backed by <mark>lambda functions</mark> and uses [MongoDB](https://www.mongodb.com/) for persistence.
          
          Thanks to its object-oriented model, the code is short and the [lambda functions](https://aws.amazon.com/lambda) are clean (they only manage HTTP issues);
          persistence is schemaless to truly take advantage of the [NoSQL](https://en.wikipedia.org/wiki/NoSQL) paradigm. 
          I used ethers.js for blockchain related stuff.

      - layout: top-middle
        title: DeeCert 
        # link: github.com/ethereum-gw
        # link_text: Project Website
        additional_links:
          - title:  public presentation article
            icon: far fa-newspaper
            url: https://www.deepit.ch/public-presentation-deecert-protocol-in-evidance/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A decentralized application for document certification, contract acceptance and property transfer that issues ERC-721 tokens.

        description: | # this will include new lines to allow paragraphs
          I was a member of the team that developed this application. 
          We used the [Universal Login](https://unilogin.io/) framework for frictionless user experience with Ethereum-like blockchain,
          IPFS as document repository, an Ethereum sidechain as default blockchain, a transaction relay infrastructure to pay gas using tokens,
          the [Arbitrary Message Bridge](https://docs.tokenbridge.net/amb-bridge/about-amb-bridge) to transfer relevant tokens to the Ethereum mainnet and vice versa,
          react.js for the user interface and no servers!    

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Erigon
        link: https://github.com/ledgerwatch/erigon
        link_text: erigon @ github
        sub_title: Ethereum Core Dev
        caption: Feb 2021 - Present
        quote: >
          Open source project
        description: | # this will include new lines to allow paragraphs
          Initially, my role was in a specialized sub-team dedicated to the development of [Silkworm](https://github.com/torquem-ch/silkworm), which is a <mark>C++</mark> version of Erigon, an Ethereum client implementation. 
          Presently, I am engaged in the quality assurance efforts for Erigon.
          
      - layout: left
        title: Blockchain Italia
        link: https://www.blockchainitalia.io/
        link_text: blockchainitalia.io
        sub_title: Blockchain Solutions Engineer - Cofounder
        caption: Aug 2018 - Apr 2023
        quote: >
          Blockchain Italia is a software house based in Milan specialized in fintech and blockchain solutions.
        description: | # this will include new lines to allow paragraphs
          I employ the <mark>blockchain</mark> and some elements of <mark>cryptography</mark> to ensure trustiness, decentralization, privacy, reliability 
          (certainty of data and code execution).

      - layout: left
        title: RSE
        #link: https://www.blockchainitalia.io/
        #link_text: blockchainitalia.io
        sub_title: Software Solution Architect - Owner
        caption: Jan 2014 - Present
        quote: >
          Mixing studies and practice
        description: | # this will include new lines to allow paragraphs
          Working as a consultant, I apply the experience that I gained designing and implementating computer systems in various sectors, to solve the customer's problems.

      - layout: left
        title: Deepit 
        link: https://www.deepit.ch/
        link_text: deepit.ch
        sub_title: Blockchain and dApp Engineer - Cofounder
        caption: Jul 2018 - Dec 2020
        quote: >
          We support companies in their approach to the blockchain world through the highest technological standards and the best expertise in the industry.
        description: | # this will include new lines to allow paragraphs
            I was part of a team of talented people who built a <mark>decentralized</mark> application for document tokenization; during our collaboration, we have also jointly developed an extension for a DeFi token to bridge it with [AAVE protocol](https://aave.com/).
            
            During this time I also sketched some ideas on the use of blockchain and cryptography to disintermediate authority in real life scenarios.
            
      - layout: left
        title: Noku 
        link: https://www.noku.io/
        link_text: noku.io
        sub_title: Blockchain Engineer
        caption: Dec 2017 - Dec 2018
        quote: >
          Noku is not a software, is not a blockchain, is not a bank. It's a community of people that want to exchange value and trust.
        description: | # this will include new lines to allow paragraphs
            I was in the ICO dev team. Later I co-designed the <mark>Ethereum</mark> smart-contracts of the TokenRaise platform which offers easy to use interfaces to create 
            your own token and launch any blockchain crowdsale.

      - layout: left
        title: Jtech
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Application Design, Engineering & Development
        caption: Jan 2014 - Dec 2022
        quote: >
          Java Enterprise Applications
        description: | # this will include new lines to allow paragraphs
            I am a partner of Jtech, a software house developing software to serve the needs of several different industries: energy governance, maritime, safety, assurance, pharmaceutical.
            
      - layout: left
        title: Telecom companies
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior/Lead Software Engineer
        caption: Feb 2001 - Nov 2013
        quote: >
          Reliability and scalability focused works
        description: | # this will include new lines to allow paragraphs
            I worked in teams responsible of evolving a proprietary <mark>telephone</mark> switch (written in C++) in a soft real-time context. 
            Relevant projects: VOIP implementation and quality/cost-based call routing; an interactive voice responder (IVR) in python with [Asterisk](http://asterisk.org/) as phone server.

            The team pioneered the <mark>devops</mark> paradigm being responsible of the software development, hardware maintenance, 
            networking configuration and service operation. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Palermo
        caption: 2000
        sub_title: MSc in Computer Engineering
        quote: >
          Linear algebra, calculus, physics, systems theory, software engineering, artificial intelligence, statistics, programming languages are fun courses ;-)
        description: | # this will include new lines to allow paragraphs
          I graduated cum laude with an experimental thesis on the control software of a generator. 
          Relevant projects: construction of a language to program a numerical control lathe; 
          construction of an ide with an interpreter for an image processing language; 
          an object oriented library to do matrix calculation;
          parallel programming on a transputer board.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have experience and expertise in: 
      - <mark>object-oriented</mark> analysis design and development
      - <mark>design patterns</mark>
      - analysis & design of <mark>concurrent</mark> <mark>reactive</mark> and <mark>distributed</mark> systems
      - <mark>serverless</mark> paradigm
      - organization of <mark>Sql</mark> and <mark>NoSql</mark> data bases
      - <mark>cloud computing</mark>
      - <mark>networking</mark>
      - <mark>web</mark> development
      - <mark>blockchain</mark> development

# to add a link: [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)      
# to link an image: ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: see GitHub for my email or book a consultation using https://about.me/rimic

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-leap-day
